input_dir: "/home/shenzhen/Datasets/dataset_with_garment_debug_100"

# Parameters
height: 768
width: 768
cfg: 5
num_steps: 30
flux_type: "FluxControlPipeline"

match_source_resolution: false
depth_mode: raw
resize_generated: false

# Debugging
max_images: null  # Set to a number for debugging, otherwise leave null if unlimited
